function result = L_matrix(n,i,x_i, u_tilde, u_tilde_prim)
    %u_tilde(2)v(2) + 4v(2)
    result = u_tilde(2) * base_function(n,i,2) + 4 * base_function(n,i,2);

    f1 = @(x) u_tilde_prim(x) .* e_deriv(n, i, x) ; %u_tilde'(x)*v'(x)
    f2 = @(x) base_function(n,i,x) .* sin(x) ; %v sinx
    f3 = @(x) u_tilde(x) .* base_function(n,i,x); %u_tilde(x) v
    
    result = result - ...
        integrate(f1,x_i(i-1),x_i(i)) - ...
        integrate(f1,x_i(i),x_i(i+1)) + ...
        integrate(f2,x_i(i-1),x_i(i))+ ...
        integrate(f2,x_i(i),x_i(i+1)) + ...
        integrate(f3,x_i(i-1),x_i(i)) + ...
        integrate(f3,x_i(i),x_i(i+1));

